### ISSUE TITLE
Package for everything does not make sense

### ISSUE THREAD

**Issue by brunolemos** [appjitsu/meteor-best-practices#1]
````
Q: Why "packages for everything"? 
A: 1) No need to use Meteor.isClient or Meteor.isServer 
unless the code is common between the client and server. 
The package.js definition file tells meteor which files should be run.
````

You can just create a 'client', a 'server' and a 'public' folder for that.
See the [Structuring your application](http://docs.meteor.com/#/full/structuringyourapp) and [Example File Structure](http://docs.meteor.com/#/full/examplefilestructure) section in Meteor docs. 

It's recommended to create packages for things that can be reusable in different projects, but the app itself shouldn't be a package :)

**Comment by appjitsu** [comment]
Actually, it makes perfect sense and it works perfectly.

**Comment by brunolemos** [comment]
hahaha Of course (y)
